
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import nodes.*;
import java.util.*;
import visitors.syntax.SyntaxVisitor;
import visitors.semantic.SemanticVisitor;
import visitors.code_generation.CodeGenerationVisitor;
import org.w3c.dom.*;
import java.io.*;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\076\000\002\002\006\000\002\002\004\000\002\003" +
    "\004\000\002\003\004\000\002\003\002\000\002\004\004" +
    "\000\002\004\002\000\002\005\005\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\006\003\000\002\007\006\000\002\007\004\000\002\010" +
    "\004\000\002\010\002\000\002\012\010\000\002\012\007" +
    "\000\002\013\004\000\002\013\002\000\002\014\007\000" +
    "\002\014\005\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\016\006\000\002\017\005\000\002\017" +
    "\005\000\002\017\006\000\002\017\007\000\002\017\006" +
    "\000\002\017\012\000\002\017\010\000\002\017\010\000" +
    "\002\011\005\000\002\011\003\000\002\021\005\000\002" +
    "\021\005\000\002\021\003\000\002\020\005\000\002\022" +
    "\005\000\002\022\005\000\002\022\005\000\002\022\005" +
    "\000\002\022\005\000\002\022\005\000\002\022\005\000" +
    "\002\022\005\000\002\022\005\000\002\022\005\000\002" +
    "\022\005\000\002\022\004\000\002\022\004\000\002\022" +
    "\005\000\002\022\003\000\002\022\003\000\002\022\003" +
    "\000\002\022\003\000\002\022\003\000\002\022\003\000" +
    "\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\004\004\005\001\002\000\004\002\201\001" +
    "\002\000\020\005\ufffd\007\007\010\010\011\013\012\012" +
    "\013\017\016\016\001\002\000\004\014\172\001\002\000" +
    "\004\014\ufff9\001\002\000\004\014\ufff8\001\002\000\020" +
    "\005\ufffd\007\007\010\010\011\013\012\012\013\017\016" +
    "\016\001\002\000\004\014\ufff6\001\002\000\004\014\ufff7" +
    "\001\002\000\020\005\ufffd\007\007\010\010\011\013\012" +
    "\012\013\017\016\016\001\002\000\004\005\165\001\002" +
    "\000\004\014\020\001\002\000\004\014\ufff5\001\002\000" +
    "\004\017\021\001\002\000\012\020\027\050\023\051\022" +
    "\052\025\001\002\000\014\007\uffe9\010\uffe9\011\uffe9\012" +
    "\uffe9\013\uffe9\001\002\000\014\007\uffea\010\uffea\011\uffea" +
    "\012\uffea\013\uffea\001\002\000\014\007\007\010\010\011" +
    "\013\012\012\013\017\001\002\000\014\007\uffe8\010\uffe8" +
    "\011\uffe8\012\uffe8\013\uffe8\001\002\000\004\020\157\001" +
    "\002\000\004\021\030\001\002\000\046\007\007\010\010" +
    "\011\013\012\012\013\017\014\uffed\017\uffed\022\uffed\026" +
    "\uffed\032\uffed\034\uffed\044\uffed\053\uffed\054\uffed\055\uffed" +
    "\056\uffed\057\uffed\060\uffed\001\002\000\020\005\uffef\007" +
    "\uffef\010\uffef\011\uffef\012\uffef\013\uffef\016\uffef\001\002" +
    "\000\034\014\047\017\043\022\ufffb\026\035\032\045\034" +
    "\036\044\052\053\037\054\054\055\041\056\050\057\042" +
    "\060\046\001\002\000\046\007\007\010\010\011\013\012" +
    "\012\013\017\014\uffed\017\uffed\022\uffed\026\uffed\032\uffed" +
    "\034\uffed\044\uffed\053\uffed\054\uffed\055\uffed\056\uffed\057" +
    "\uffed\060\uffed\001\002\000\034\014\uffee\017\uffee\022\uffee" +
    "\026\uffee\032\uffee\034\uffee\044\uffee\053\uffee\054\uffee\055" +
    "\uffee\056\uffee\057\uffee\060\uffee\001\002\000\026\014\063" +
    "\017\043\026\035\044\052\053\037\054\054\055\041\056" +
    "\050\057\042\060\046\001\002\000\004\017\151\001\002" +
    "\000\040\006\uffc7\015\uffc7\020\uffc7\024\uffc7\025\uffc7\026" +
    "\uffc7\027\uffc7\030\uffc7\037\uffc7\040\uffc7\041\uffc7\042\uffc7" +
    "\043\uffc7\045\uffc7\046\uffc7\001\002\000\036\015\147\020" +
    "\uffda\024\uffda\025\067\026\064\027\074\030\072\037\073" +
    "\040\066\041\075\042\071\043\070\045\065\046\076\001" +
    "\002\000\040\006\uffc4\015\uffc4\020\uffc4\024\uffc4\025\uffc4" +
    "\026\uffc4\027\uffc4\030\uffc4\037\uffc4\040\uffc4\041\uffc4\042" +
    "\uffc4\043\uffc4\045\uffc4\046\uffc4\001\002\000\040\006\uffca" +
    "\015\uffca\020\uffca\024\uffca\025\uffca\026\uffca\027\uffca\030" +
    "\uffca\037\uffca\040\uffca\041\uffca\042\uffca\043\uffca\045\uffca" +
    "\046\uffca\001\002\000\026\014\063\017\043\026\035\044" +
    "\052\053\037\054\054\055\041\056\050\057\042\060\046" +
    "\001\002\000\004\022\144\001\002\000\004\017\132\001" +
    "\002\000\040\006\uffc9\015\uffc9\020\uffc9\024\uffc9\025\uffc9" +
    "\026\uffc9\027\uffc9\030\uffc9\037\uffc9\040\uffc9\041\uffc9\042" +
    "\uffc9\043\uffc9\045\uffc9\046\uffc9\001\002\000\042\015\113" +
    "\017\114\023\uffdd\024\uffc8\025\uffc8\026\uffc8\027\uffc8\030" +
    "\uffc8\031\115\037\uffc8\040\uffc8\041\uffc8\042\uffc8\043\uffc8" +
    "\045\uffc8\046\uffc8\001\002\000\040\006\uffc5\015\uffc5\020" +
    "\uffc5\024\uffc5\025\uffc5\026\uffc5\027\uffc5\030\uffc5\037\uffc5" +
    "\040\uffc5\041\uffc5\042\uffc5\043\uffc5\045\uffc5\046\uffc5\001" +
    "\002\000\036\002\ufffb\014\047\017\043\022\ufffb\026\035" +
    "\032\045\034\036\044\052\053\037\054\054\055\041\056" +
    "\050\057\042\060\046\001\002\000\026\014\063\017\043" +
    "\026\035\044\052\053\037\054\054\055\041\056\050\057" +
    "\042\060\046\001\002\000\004\023\060\001\002\000\040" +
    "\006\uffc6\015\uffc6\020\uffc6\024\uffc6\025\uffc6\026\uffc6\027" +
    "\uffc6\030\uffc6\037\uffc6\040\uffc6\041\uffc6\042\uffc6\043\uffc6" +
    "\045\uffc6\046\uffc6\001\002\000\004\024\056\001\002\000" +
    "\004\006\057\001\002\000\036\002\uffe5\014\uffe5\017\uffe5" +
    "\022\uffe5\026\uffe5\032\uffe5\034\uffe5\044\uffe5\053\uffe5\054" +
    "\uffe5\055\uffe5\056\uffe5\057\uffe5\060\uffe5\001\002\000\004" +
    "\006\061\001\002\000\036\002\uffe6\014\uffe6\017\uffe6\022" +
    "\uffe6\026\uffe6\032\uffe6\034\uffe6\044\uffe6\053\uffe6\054\uffe6" +
    "\055\uffe6\056\uffe6\057\uffe6\060\uffe6\001\002\000\040\006" +
    "\uffcc\015\uffcc\020\uffcc\024\uffcc\025\067\026\064\027\074" +
    "\030\072\037\073\040\066\041\075\042\071\043\070\045" +
    "\uffcc\046\uffcc\001\002\000\040\006\uffc8\015\uffc8\020\uffc8" +
    "\024\uffc8\025\uffc8\026\uffc8\027\uffc8\030\uffc8\037\uffc8\040" +
    "\uffc8\041\uffc8\042\uffc8\043\uffc8\045\uffc8\046\uffc8\001\002" +
    "\000\026\014\063\017\043\026\035\044\052\053\037\054" +
    "\054\055\041\056\050\057\042\060\046\001\002\000\026" +
    "\014\063\017\043\026\035\044\052\053\037\054\054\055" +
    "\041\056\050\057\042\060\046\001\002\000\026\014\063" +
    "\017\043\026\035\044\052\053\037\054\054\055\041\056" +
    "\050\057\042\060\046\001\002\000\026\014\063\017\043" +
    "\026\035\044\052\053\037\054\054\055\041\056\050\057" +
    "\042\060\046\001\002\000\026\014\063\017\043\026\035" +
    "\044\052\053\037\054\054\055\041\056\050\057\042\060" +
    "\046\001\002\000\026\014\063\017\043\026\035\044\052" +
    "\053\037\054\054\055\041\056\050\057\042\060\046\001" +
    "\002\000\026\014\063\017\043\026\035\044\052\053\037" +
    "\054\054\055\041\056\050\057\042\060\046\001\002\000" +
    "\026\014\063\017\043\026\035\044\052\053\037\054\054" +
    "\055\041\056\050\057\042\060\046\001\002\000\026\014" +
    "\063\017\043\026\035\044\052\053\037\054\054\055\041" +
    "\056\050\057\042\060\046\001\002\000\026\014\063\017" +
    "\043\026\035\044\052\053\037\054\054\055\041\056\050" +
    "\057\042\060\046\001\002\000\026\014\063\017\043\026" +
    "\035\044\052\053\037\054\054\055\041\056\050\057\042" +
    "\060\046\001\002\000\040\006\uffd3\015\uffd3\020\uffd3\024" +
    "\uffd3\025\067\026\064\027\074\030\072\037\073\040\066" +
    "\041\075\042\071\043\070\045\uffd3\046\uffd3\001\002\000" +
    "\040\006\uffd0\015\uffd0\020\uffd0\024\uffd0\025\067\026\064" +
    "\027\074\030\072\037\uffd0\040\uffd0\041\uffd0\042\uffd0\043" +
    "\uffd0\045\uffd0\046\uffd0\001\002\000\040\006\uffd6\015\uffd6" +
    "\020\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030\uffd6\037" +
    "\uffd6\040\uffd6\041\uffd6\042\uffd6\043\uffd6\045\uffd6\046\uffd6" +
    "\001\002\000\040\006\uffd2\015\uffd2\020\uffd2\024\uffd2\025" +
    "\067\026\064\027\074\030\072\037\uffd2\040\uffd2\041\uffd2" +
    "\042\uffd2\043\uffd2\045\uffd2\046\uffd2\001\002\000\040\006" +
    "\uffd5\015\uffd5\020\uffd5\024\uffd5\025\uffd5\026\uffd5\027\uffd5" +
    "\030\uffd5\037\uffd5\040\uffd5\041\uffd5\042\uffd5\043\uffd5\045" +
    "\uffd5\046\uffd5\001\002\000\040\006\uffcf\015\uffcf\020\uffcf" +
    "\024\uffcf\025\067\026\064\027\074\030\072\037\uffcf\040" +
    "\uffcf\041\uffcf\042\uffcf\043\uffcf\045\uffcf\046\uffcf\001\002" +
    "\000\040\006\uffce\015\uffce\020\uffce\024\uffce\025\067\026" +
    "\064\027\074\030\072\037\uffce\040\uffce\041\uffce\042\uffce" +
    "\043\uffce\045\uffce\046\uffce\001\002\000\040\006\uffd8\015" +
    "\uffd8\020\uffd8\024\uffd8\025\uffd8\026\uffd8\027\074\030\072" +
    "\037\uffd8\040\uffd8\041\uffd8\042\uffd8\043\uffd8\045\uffd8\046" +
    "\uffd8\001\002\000\040\006\uffd1\015\uffd1\020\uffd1\024\uffd1" +
    "\025\067\026\064\027\074\030\072\037\uffd1\040\uffd1\041" +
    "\uffd1\042\uffd1\043\uffd1\045\uffd1\046\uffd1\001\002\000\040" +
    "\006\uffd4\015\uffd4\020\uffd4\024\uffd4\025\067\026\064\027" +
    "\074\030\072\037\073\040\066\041\075\042\071\043\070" +
    "\045\uffd4\046\uffd4\001\002\000\040\006\uffd7\015\uffd7\020" +
    "\uffd7\024\uffd7\025\uffd7\026\uffd7\027\074\030\072\037\uffd7" +
    "\040\uffd7\041\uffd7\042\uffd7\043\uffd7\045\uffd7\046\uffd7\001" +
    "\002\000\006\002\ufffc\022\ufffc\001\002\000\026\014\130" +
    "\017\043\026\035\044\052\053\037\054\054\055\041\056" +
    "\050\057\042\060\046\001\002\000\030\014\120\017\043" +
    "\020\121\026\035\044\052\053\037\054\054\055\041\056" +
    "\050\057\042\060\046\001\002\000\026\014\063\017\043" +
    "\026\035\044\052\053\037\054\054\055\041\056\050\057" +
    "\042\060\046\001\002\000\032\006\117\025\067\026\064" +
    "\027\074\030\072\037\073\040\066\041\075\042\071\043" +
    "\070\045\065\046\076\001\002\000\036\002\uffe4\014\uffe4" +
    "\017\uffe4\022\uffe4\026\uffe4\032\uffe4\034\uffe4\044\uffe4\053" +
    "\uffe4\054\uffe4\055\uffe4\056\uffe4\057\uffe4\060\uffe4\001\002" +
    "\000\036\015\126\020\uffc8\024\uffc8\025\uffc8\026\uffc8\027" +
    "\uffc8\030\uffc8\037\uffc8\040\uffc8\041\uffc8\042\uffc8\043\uffc8" +
    "\045\uffc8\046\uffc8\001\002\000\004\006\125\001\002\000" +
    "\004\020\123\001\002\000\004\006\124\001\002\000\036" +
    "\002\uffe3\014\uffe3\017\uffe3\022\uffe3\026\uffe3\032\uffe3\034" +
    "\uffe3\044\uffe3\053\uffe3\054\uffe3\055\uffe3\056\uffe3\057\uffe3" +
    "\060\uffe3\001\002\000\036\002\uffe2\014\uffe2\017\uffe2\022" +
    "\uffe2\026\uffe2\032\uffe2\034\uffe2\044\uffe2\053\uffe2\054\uffe2" +
    "\055\uffe2\056\uffe2\057\uffe2\060\uffe2\001\002\000\026\014" +
    "\120\017\043\026\035\044\052\053\037\054\054\055\041" +
    "\056\050\057\042\060\046\001\002\000\006\020\uffdb\024" +
    "\uffdb\001\002\000\036\015\113\023\uffdd\024\uffc8\025\uffc8" +
    "\026\uffc8\027\uffc8\030\uffc8\037\uffc8\040\uffc8\041\uffc8\042" +
    "\uffc8\043\uffc8\045\uffc8\046\uffc8\001\002\000\004\023\uffde" +
    "\001\002\000\026\014\063\017\043\026\035\044\052\053" +
    "\037\054\054\055\041\056\050\057\042\060\046\001\002" +
    "\000\032\020\134\025\067\026\064\027\074\030\072\037" +
    "\073\040\066\041\075\042\071\043\070\045\065\046\076" +
    "\001\002\000\004\033\135\001\002\000\004\021\136\001" +
    "\002\000\034\014\047\017\043\022\ufffb\026\035\032\045" +
    "\034\036\044\052\053\037\054\054\055\041\056\050\057" +
    "\042\060\046\001\002\000\040\002\uffe0\014\uffe0\017\uffe0" +
    "\022\uffe0\026\uffe0\032\uffe0\034\uffe0\036\140\044\uffe0\053" +
    "\uffe0\054\uffe0\055\uffe0\056\uffe0\057\uffe0\060\uffe0\001\002" +
    "\000\004\021\136\001\002\000\036\002\uffe1\014\uffe1\017" +
    "\uffe1\022\uffe1\026\uffe1\032\uffe1\034\uffe1\044\uffe1\053\uffe1" +
    "\054\uffe1\055\uffe1\056\uffe1\057\uffe1\060\uffe1\001\002\000" +
    "\004\022\143\001\002\000\040\002\uffd9\014\uffd9\017\uffd9" +
    "\022\uffd9\026\uffd9\032\uffd9\034\uffd9\036\uffd9\044\uffd9\053" +
    "\uffd9\054\uffd9\055\uffd9\056\uffd9\057\uffd9\060\uffd9\001\002" +
    "\000\020\005\uffe7\007\uffe7\010\uffe7\011\uffe7\012\uffe7\013" +
    "\uffe7\016\uffe7\001\002\000\032\020\146\025\067\026\064" +
    "\027\074\030\072\037\073\040\066\041\075\042\071\043" +
    "\070\045\065\046\076\001\002\000\040\006\uffcb\015\uffcb" +
    "\020\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030\uffcb\037" +
    "\uffcb\040\uffcb\041\uffcb\042\uffcb\043\uffcb\045\uffcb\046\uffcb" +
    "\001\002\000\026\014\120\017\043\026\035\044\052\053" +
    "\037\054\054\055\041\056\050\057\042\060\046\001\002" +
    "\000\006\020\uffdc\024\uffdc\001\002\000\026\014\063\017" +
    "\043\026\035\044\052\053\037\054\054\055\041\056\050" +
    "\057\042\060\046\001\002\000\032\020\153\025\067\026" +
    "\064\027\074\030\072\037\073\040\066\041\075\042\071" +
    "\043\070\045\065\046\076\001\002\000\004\035\154\001" +
    "\002\000\004\021\136\001\002\000\036\002\uffdf\014\uffdf" +
    "\017\uffdf\022\uffdf\026\uffdf\032\uffdf\034\uffdf\044\uffdf\053" +
    "\uffdf\054\uffdf\055\uffdf\056\uffdf\057\uffdf\060\uffdf\001\002" +
    "\000\040\006\uffcd\015\uffcd\020\uffcd\024\uffcd\025\uffcd\026" +
    "\uffcd\027\uffcd\030\uffcd\037\uffcd\040\uffcd\041\uffcd\042\uffcd" +
    "\043\uffcd\045\uffcd\046\uffcd\001\002\000\004\021\030\001" +
    "\002\000\020\005\ufff0\007\ufff0\010\ufff0\011\ufff0\012\ufff0" +
    "\013\ufff0\016\ufff0\001\002\000\004\014\162\001\002\000" +
    "\006\015\163\020\uffeb\001\002\000\010\050\023\051\022" +
    "\052\025\001\002\000\004\020\uffec\001\002\000\034\002" +
    "\ufffb\014\047\017\043\026\035\032\045\034\036\044\052" +
    "\053\037\054\054\055\041\056\050\057\042\060\046\001" +
    "\002\000\004\002\001\001\002\000\004\005\uffff\001\002" +
    "\000\004\005\ufffe\001\002\000\004\006\200\001\002\000" +
    "\010\006\ufff1\015\ufff1\031\174\001\002\000\006\006\ufff3" +
    "\015\176\001\002\000\026\014\063\017\043\026\035\044" +
    "\052\053\037\054\054\055\041\056\050\057\042\060\046" +
    "\001\002\000\034\006\ufff2\015\ufff2\025\067\026\064\027" +
    "\074\030\072\037\073\040\066\041\075\042\071\043\070" +
    "\045\065\046\076\001\002\000\004\014\172\001\002\000" +
    "\004\006\ufff4\001\002\000\052\005\ufffa\007\ufffa\010\ufffa" +
    "\011\ufffa\012\ufffa\013\ufffa\014\ufffa\016\ufffa\017\ufffa\022" +
    "\ufffa\026\ufffa\032\ufffa\034\ufffa\044\ufffa\053\ufffa\054\ufffa" +
    "\055\ufffa\056\ufffa\057\ufffa\060\ufffa\001\002\000\004\002" +
    "\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\004\002\003\001\001\000\002\001\001\000" +
    "\012\003\014\005\013\006\005\012\010\001\001\000\004" +
    "\007\170\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\003\167\005\013\006\005\012\010\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\003\166\005\013\006" +
    "\005\012\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\014\025\015" +
    "\023\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\006\160\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\030\001\001\000\010\005\032\006\005\013\031" +
    "\001\001\000\002\001\001\000\014\004\043\011\052\017" +
    "\050\021\054\022\037\001\001\000\010\005\032\006\005" +
    "\013\033\001\001\000\002\001\001\000\004\022\155\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\022\144\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\004\111\011" +
    "\052\017\050\021\054\022\037\001\001\000\004\022\061" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\110\001\001\000\004\022\107\001\001\000\004" +
    "\022\106\001\001\000\004\022\105\001\001\000\004\022" +
    "\104\001\001\000\004\022\103\001\001\000\004\022\102" +
    "\001\001\000\004\022\101\001\001\000\004\022\100\001" +
    "\001\000\004\022\077\001\001\000\004\022\076\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\011\130" +
    "\021\126\022\037\001\001\000\006\021\121\022\037\001" +
    "\001\000\004\022\115\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\021\126\022\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\132\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\020\136\001" +
    "\001\000\014\004\141\011\052\017\050\021\054\022\037" +
    "\001\001\000\002\001\001\000\004\020\140\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\021" +
    "\147\022\037\001\001\000\002\001\001\000\004\022\151" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\020" +
    "\154\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\157\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\014\163\015\023\001\001\000\002" +
    "\001\001\000\014\004\165\011\052\017\050\021\054\022" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\172\001\001\000" +
    "\002\001\001\000\004\022\174\001\001\000\002\001\001" +
    "\000\004\007\176\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

	symbol = lexer.next_token();
  	return symbol;

    }


    private Lexer lexer;
    private File file;
    private Symbol symbol;
    
    public ParserCup( File file ) {
        this();
        this.file = file;
        try {
            lexer = new Lexer( new FileReader( file ) );
        }
        catch ( IOException exception ) {
        	throw new Error( "Unable to open file \"" + file + "\"" );
        }
    }

    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");

        m.append(" : "+message+" "+"row "+symbol.left+":"+" column "+symbol.right);
   
        System.err.println(m);
      }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCup$actions {
  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action_part00000000(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Programma ::= HEAD Decls START Statements 
            {
              Program RESULT =null;
		int declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Decl> decls = (ArrayList<Decl>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Statement> stmts = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tPROGRAM COMPLETE"); RESULT = new Program(decls,stmts); 
														SyntaxVisitor sv = new SyntaxVisitor();
														sv.appendRoot((Element)sv.visit(RESULT));
                                                        sv.toXml();

														SemanticVisitor sm = new SemanticVisitor();
														sm.appendRoot((Element)sm.visit(RESULT));
                                                        sm.toXml();	

														CodeGenerationVisitor cg = new CodeGenerationVisitor(sm.getStackOfTable(), sm.getListSymTable());
														PrintWriter out = new PrintWriter("yaspl.c");
                                                        out.println(cg.visit(RESULT));
                                                        out.close();
														
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Programma",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Programma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Decls ::= Var_decl Decls 
            {
              ArrayList<Decl> RESULT =null;
		int var_declleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int var_declright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		VarDeclaration var_decl = (VarDeclaration)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Decl> decls = (ArrayList<Decl>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 decls.add(var_decl); System.out.println("\tDECLSS 1 COMPLETATO"+decls); RESULT = decls; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Decls",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Decls ::= Def_decl Decls 
            {
              ArrayList<Decl> RESULT =null;
		int def_declleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int def_declright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		FunctionDeclaration def_decl = (FunctionDeclaration)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Decl> decls = (ArrayList<Decl>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 decls.add(def_decl); System.out.println("\tDECLSS 2 COMPLETATO"+decls); RESULT = decls; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Decls",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Decls ::= 
            {
              ArrayList<Decl> RESULT =null;
		 RESULT = new ArrayList<Decl>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Decls",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Statements ::= Stat Statements 
            {
              ArrayList<Statement> RESULT =null;
		int statleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int statright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Statement stat = (Statement)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Statement> stmts = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tSTATEMENTS COMPLETE"); stmts.add(stat); RESULT = stmts; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Statements",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Statements ::= 
            {
              ArrayList<Statement> RESULT =null;
		 RESULT = new ArrayList<Statement>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Statements",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Var_decl ::= Type Var_decls_init SEMI 
            {
              VarDeclaration RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int var_decls_initleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int var_decls_initright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<VarDeclarationInit> var_decls_init = (ArrayList<VarDeclarationInit>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 System.out.println("\tVAR_DECLLL COMPLETATO"); RESULT = new VarDeclaration(type,var_decls_init); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_decl",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= INT 
            {
              Type RESULT =null;
		 System.out.println("\tType = int"); RESULT = new Type("int"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= BOOL 
            {
              Type RESULT =null;
		 RESULT = new Type("bool"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= DOUBLE 
            {
              Type RESULT =null;
		 RESULT = new Type("double"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Type ::= STRING 
            {
              Type RESULT =null;
		 RESULT = new Type("string"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Type ::= CHAR 
            {
              Type RESULT =null;
		 RESULT = new Type("char"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Var_decls_init ::= ID Var_init_value COMMA Var_decls_init 
            {
              ArrayList<VarDeclarationInit> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int var_init_valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int var_init_valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		VarInitValue var_init_value = (VarInitValue)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int var_decls_initleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int var_decls_initright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<VarDeclarationInit> var_decls_init = (ArrayList<VarDeclarationInit>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tVar_decls_init 1 COMPLETE"); var_decls_init.add(new VarDeclarationInit(new Identifier(id), var_init_value)); RESULT = var_decls_init; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_decls_init",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Var_decls_init ::= ID Var_init_value 
            {
              ArrayList<VarDeclarationInit> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int var_init_valueleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int var_init_valueright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		VarInitValue var_init_value = (VarInitValue)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tVar_decls_init 2 COMPLETE"); RESULT = new ArrayList<>(); RESULT.add(new VarDeclarationInit(new Identifier(id), var_init_value)); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_decls_init",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Var_init_value ::= ASSIGN Expr 
            {
              VarInitValue RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tVar_init_value COMPLETE"); RESULT = new VarInitValue(new AssignOP(expr)); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_init_value",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Var_init_value ::= 
            {
              VarInitValue RESULT =null;
		 RESULT = null; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_init_value",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Def_decl ::= DEF ID LPAR Par_decls RPAR Body 
            {
              FunctionDeclaration RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int par_declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int par_declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<ParameterDeclaration> par_decls = (ArrayList<ParameterDeclaration>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Body body = (Body)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new FunctionDeclaration(new Identifier(id), par_decls, body); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Def_decl",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Def_decl ::= DEF ID LPAR RPAR Body 
            {
              FunctionDeclaration RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Body body = (Body)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new FunctionDeclaration(new Identifier(id), body); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Def_decl",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Var_decls ::= Var_decl Var_decls 
            {
              ArrayList<VarDeclaration> RESULT =null;
		int var_declleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int var_declright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		VarDeclaration var_decl = (VarDeclaration)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int var_declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int var_declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<VarDeclaration> var_decls = (ArrayList<VarDeclaration>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 var_decls.add(var_decl); RESULT = var_decls; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_decls",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Var_decls ::= 
            {
              ArrayList<VarDeclaration> RESULT =null;
		 RESULT = new ArrayList<VarDeclaration>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Var_decls",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Par_decls ::= Par_type Type ID COMMA Par_decls 
            {
              ArrayList<ParameterDeclaration> RESULT =null;
		int par_typeleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int par_typeright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		ParameterType par_type = (ParameterType)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int par_declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int par_declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<ParameterDeclaration> par_decls = (ArrayList<ParameterDeclaration>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 par_decls.add(new ParameterDeclaration(par_type, type, new Identifier(id))); RESULT = par_decls; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Par_decls",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Par_decls ::= Par_type Type ID 
            {
              ArrayList<ParameterDeclaration> RESULT =null;
		int par_typeleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int par_typeright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ParameterType par_type = (ParameterType)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Type type = (Type)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(new ParameterDeclaration(par_type, type, new Identifier(id))); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Par_decls",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Par_type ::= IN 
            {
              ParameterType RESULT =null;
		 RESULT = new ParameterType("in"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Par_type",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Par_type ::= OUT 
            {
              ParameterType RESULT =null;
		 RESULT = new ParameterType("out"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Par_type",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Par_type ::= INOUT 
            {
              ParameterType RESULT =null;
		 RESULT = new ParameterType("inout"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Par_type",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Body ::= LGPAR Var_decls Statements RGPAR 
            {
              Body RESULT =null;
		int var_declsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int var_declsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<VarDeclaration> var_decls = (ArrayList<VarDeclaration>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Statement> stmts = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new Body(var_decls, stmts); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Body",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Stat ::= Vars READ SEMI 
            {
              Statement RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Identifier> vars = (ArrayList<Identifier>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		 System.out.println("\tStat::= ReadOP"); RESULT = new ReadOP(vars); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Stat ::= Args WRITE SEMI 
            {
              Statement RESULT =null;
		int argsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Expression> args = (ArrayList<Expression>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		 System.out.println("\tStat::= WriteOP"); RESULT = new WriteOP(args); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Stat ::= ID ASSIGN Expr SEMI 
            {
              Statement RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new AssignOP(new Identifier(id), expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Stat ::= ID LPAR Args RPAR SEMI 
            {
              Statement RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Expression> args = (ArrayList<Expression>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		 RESULT = new CallOP(new Identifier(id), args); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Stat ::= ID LPAR RPAR SEMI 
            {
              Statement RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		 RESULT = new CallOP(new Identifier(id)); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Stat ::= IF LPAR Expr RPAR THEN Comp_stat ELSE Comp_stat 
            {
              Statement RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int comp_statleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int comp_statright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		CompStatement comp_stat = (CompStatement)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int comp_stat_elseleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int comp_stat_elseright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		CompStatement comp_stat_else = (CompStatement)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new IfThenElseOP(expr, comp_stat, comp_stat_else); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Stat ::= IF LPAR Expr RPAR THEN Comp_stat 
            {
              Statement RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int comp_statleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int comp_statright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		CompStatement comp_stat = (CompStatement)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new IfThenOP(expr, comp_stat); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Stat ::= WHILE LPAR Expr RPAR DO Comp_stat 
            {
              Statement RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int comp_statleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int comp_statright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		CompStatement comp_stat = (CompStatement)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new WhileOP(expr, comp_stat); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Stat",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Vars ::= ID COMMA Vars 
            {
              ArrayList<Identifier> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int varsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Identifier> vars = (ArrayList<Identifier>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 vars.add(new Identifier(id)); RESULT = vars; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Vars",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Vars ::= ID 
            {
              ArrayList<Identifier> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(new Identifier(id)); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Vars",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Args ::= Expr COMMA Args 
            {
              ArrayList<Expression> RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Expression> args = (ArrayList<Expression>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tArgs 1 "); args.add(expr); RESULT = args; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Args",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Args ::= ID COMMA Args 
            {
              ArrayList<Expression> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Expression> args = (ArrayList<Expression>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tArgs ID "); args.add(new Identifier(id)); RESULT = args; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Args",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Args ::= Expr 
            {
              ArrayList<Expression> RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tArgs 2 "); RESULT = new ArrayList<>(); RESULT.add(expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Args",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Comp_stat ::= LGPAR Statements RGPAR 
            {
              CompStatement RESULT =null;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Statement> stmts = (ArrayList<Statement>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = new CompStatement(stmts); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Comp_stat",14, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Expr ::= Expr PLUS Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ArithOP(expr1, expr2, "AddOP"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Expr ::= Expr MINUS Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ArithOP(expr1, expr2, "DiffOP"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Expr ::= Expr TIMES Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ArithOP(expr1, expr2, "MulOP"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Expr ::= Expr DIV Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new ArithOP(expr1, expr2, "DivOP"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Expr ::= Expr AND Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BoolOP(expr1, expr2, "ANDOp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Expr ::= Expr OR Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new BoolOP(expr1, expr2, "OROp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Expr ::= Expr GT Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new RelOP(expr1, expr2, "GTOp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Expr ::= Expr GE Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new RelOP(expr1, expr2, "GEOp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Expr ::= Expr LT Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new RelOP(expr1, expr2, "LTOp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Expr ::= Expr LE Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new RelOP(expr1, expr2, "LEOp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Expr ::= Expr EQ Expr 
            {
              Expression RESULT =null;
		int expr1left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int expr1right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Expression expr1 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int expr2left = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int expr2right = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr2 = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new RelOP(expr1, expr2, "EQOp"); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // Expr ::= MINUS Expr 
            {
              Expression RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new UminusOP(expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // Expr ::= NOT Expr 
            {
              Expression RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new NotOP(expr); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Expr ::= LPAR Expr RPAR 
            {
              Expression RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		 RESULT = expr; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Expr ::= TRUE 
            {
              Expression RESULT =null;
		 RESULT = new TrueOP(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Expr ::= FALSE 
            {
              Expression RESULT =null;
		 RESULT = new FalseOP(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Expr ::= ID 
            {
              Expression RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tID"); RESULT = new Identifier(id); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Expr ::= INT_CONST 
            {
              Expression RESULT =null;
		int icleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int icright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Integer ic = (Integer)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 System.out.println("\tExpr ::= INT_CONST"); RESULT = new IntConst(ic); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Expr ::= DOUBLE_CONST 
            {
              Expression RESULT =null;
		int dcleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dcright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Double dc = (Double)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new DoubleConst(dc); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Expr ::= CHAR_CONST 
            {
              Expression RESULT =null;
		int ccleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int ccright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Character cc = (Character)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new CharConst(cc); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Expr ::= STRING_CONST 
            {
              Expression RESULT =null;
		int scleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int scright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String sc = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		 RESULT = new StringConst(sc); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("Expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
              return CUP$ParserCup$do_action_part00000000(
                               CUP$ParserCup$act_num,
                               CUP$ParserCup$parser,
                               CUP$ParserCup$stack,
                               CUP$ParserCup$top);
    }
}

}
